apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: AWS-ElasticSearch
    category: Analysis
    version: 7.4.0
spec:
  inputs:
    - name: elasticsearchVersion
      inputType: String
      description: 'elsatic search version'
      defaultValue: 7.4
      require: false
    - name: domainName
      inputType: String
      description: 'doamin name for es'
      require: true
    - name: dataInstanceCount
      inputType: Number
      description: 'number of data instance'
      defaultValue: 2
      require: false
    - name: dataInstanceType
      inputType: String
      description: 'instance type for data node'
      defaultValue: r5.large.elasticsearch
      require: false
    - name: instanceVolumeSize
      inputType: Number
      description: 'storage size'
      defaultValue: 20
      require: false
    - name: instanceVolumeType
      inputType: String
      description: 'type of storage'
      defaultValue: gp2
      require: false
    - name: masterInstanceCount
      inputType: Number
      description: 'number of master node'
      defaultValue: 2
      require: false
    - name: masterInstanceType
      inputType: String
      description: 'instance type for master node'
      defaultValue: r5.large.elasticsearch
      require: false
    - name: masterUserName
      inputType: Secret
      description: 'user'
      require: true
    - name: masterUserPassword
      inputType: Secret
      description: 'password'
      require: true


  postRun:
    stages:
      - name: UpdateConfigMap
        command: |  
          aws es update-elasticsearch-domain-config \
          --domain-name $(self.inputs.domainName) \
          --advanced-security-options \
          'Enabled=true,InternalUserDatabaseEnabled=true,MasterUserOptions={MasterUserName="$(self.inputs.masterUserName)",MasterUserPassword="$(self.inputs.masterUserPassword)"}'

  outputs:
    # String
    - name: domainName
      outputType: String
      description: AWS::ElasticSearch::Domain
    - name: domainEndpoint
      outputType: String
      description: AWS::ElasticSearch::Domain

  # Notes are description list for addtional information.
  notes: []

