apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Ambassador
    category: ContainerApplication
    version: 1.5.0
    dependentOnVendorService: EKS

# Specification
spec: 
  preRun:
    stages:
      - name: InstallAmbassador
        command: |
            kubectl apply -f https://www.getambassador.io/yaml/aes-crds.yaml 
            kubectl wait --for condition=established --timeout=90s crd -lproduct=aes 
            kubectl apply -f https://www.getambassador.io/yaml/aes.yaml
            kubectl -n ambassador wait --for condition=available --timeout=90s deploy -lproduct=aes
  inputs:
    # String
    - name: clusterName
      inputType: String
      require: true
    # String
    - name: masterRoleARN
      inputType: String
      require: true


          
  # Ouptputs represnt output value after launched, for 'ContainerApplication' might need leverage specific command to retrive output.
  outputs:
    # String
    - name: ambassadorEndpoint
      outputType: String
      defaultValueCommand:  kubectl get -n ambassador service ambassador -o "go-template={{range .status.loadBalancer.ingress}}{{or .ip .hostname}}{{end}}"
      description: Custom::String


  notes: []

