# Service account for spyservice 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spyservice-account
automountServiceAccountToken: false

---
# Secret attach to service account 
apiVersion: v1
kind: Secret
metadata:
  name: spyservice-account-secret
  annotations: 
    kubernetes.io/service-account.name: spyservice-account
type: kubernetes.io/service-account-token

---
# Define role with necesary permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spyservice-role
  labels:
    app: spyservice
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - services
  - endpoints
  - pods
  - nodes/proxy
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
# Binding role with service account 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spyservice-role-binding
  labels:
    app: spyservice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spyservice-role
subjects:
- kind: ServiceAccount
  name: spyservice-account
  namespace: default