# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# list of resource config to be applied
resources:
- account.yaml
- spy-deployment.yaml
- spy-service.yaml

# # namespace to deploy all resources to
# namespace: go-bumblebee


commonLabels:
  author: cc
