apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: EFS
    category: Storage
    version: 0.1.0
spec:
  dependencies:
    - name: network
      tileReference: Network0
      tileVersion: 0.0.1
  # Inputs are input parameters when lauching 
  inputs:
    # CDKObject
    - name: vpc
      inputType: CDKObject
      description: 'Refer to VPC object on Tile - Network0'
      dependencies:
        - name: network
          field: baseVpc
      require: false

  outputs:
    # String
    - name: fileSystemId
      outputType: String
      description: AWS::EFS::FileSystem

  # Notes are description list for addtional information.
  notes: []

