# API version
apiVersion: mahjong.io/v1alpha1
# Kind of entity
kind: Tile
# Metadata
metadata:
    # Name of entity
    name: Eks0
    # Category of entity
    category: ContainerProvider
    # Vendor
    vendorService: EKS
    # Version of entity
    version: 0.0.1
# Specification
spec:
  # Dependencies represent dependency with other Tile
  dependencies:
      # As a reference name 
    - name: network
      # Tile name
      tileReference: Network0
      # Tile version
      tileVersion: 0.0.1
  # Inputs are input parameters when lauching 
  inputs:
    # CDKObject
    - name: vpc
      inputType: CDKObject
      description: 'Refer to VPC object on Tile - Network0'
      dependencies:
          # Reference name in Dependencies
        - name: network
          # Filed name in refered Tile
          field: baseVpc
      # Input is mandatory or not, true is mandatory and false is optional
      require: false
    # CDKObject[]
    - name: vpcSubnets
      inputType: CDKObject[]
      description: ''
      dependencies:
        - name: network
          field: publicSubnet1
        - name: network
          field: publicSubnet2
        - name: network
          field: privateSubnet1
        - name: network
          field: privateSubnet2
      require: false
    # String
    - name: clusterName
      inputType: String
      description: ''
      defaultValue: default-eks-cluster
      require: true
    # Number/ default: 2
    - name: capacity
      inputType: Number
      description: ''
      defaultValue: 2
      require: false
    # String/ default: 'c5.large'
    - name: capacityInstance
      inputType: String
      description: ''
      defaultValue: 'c5.large'
      require: false
    # String/ default: '1.15'
    - name: version
      inputType: String
      description: ''
      defaultValue: '1.15'
      require: false
  # Ouptputs represnt output value after launched, for 'ContainerApplication' might need leverage specific command to retrive output.
  outputs:
    # String
    - name: clusterName
      outputType: String
      description: AWS::EKS::Cluster.Name
    # String
    - name: clusterArn
      outputType: String
      description: AWS::EKS::Cluster.ARN          
    # String
    - name: clusterEndpoint
      outputType: String
      description: AWS::EKS::Cluster.Endpoint
    # String
    - name: masterRoleARN
      outputType: String
      description: AWS::IAM::Role.ARN

  # Notes are description list for addtional information.
  notes:
    - "Tag public subnets with 'kubernetes.io/role/elb=1'"
    - "Tag priavte subnets with 'kubernetes.io/role/internal-elb=1'"

