apiVersion: v1
kind: Service
metadata:
  name: gateservice
spec: 
  type: ClusterIP
  selector:
    app: gateservice
  ports:
  - name: http
    port: 9010
    targetPort: 9010
  - name: grpc
    port: 9020
    targetPort: 9020
  - name: graphql
    port: 9030
    targetPort: 9030
  - name: websocket
    port: 9040
    targetPort: 9040     
  - name: tcp
    port: 9050
    targetPort: 9050