apiVersion: apps/v1
kind: Deployment 
metadata:
  name: airservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: airservice 
  template:
    metadata:
      labels: 
        app: airservice 
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: air-go-bumblebee
        image:  herochinese/go-bumblebee-air:front-end-site-v1
        ports:
          - name: http
            containerPort: 9011
        resources:
          requests: 
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi