apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: go-bumblebee-jazz
spec:
  template:
    tiles:
      tileGoBumblebeeJazz071:
        tileReference: Go-Bumblebee-Jazz
        tileVersion: 0.7.1
        inputs:
          - name: clusterName
            inputValue: <EKS CLuster Name>
          - name: masterRoleARN
            inputValue: <IAM ROLE ARN>
          - name: accessToken
            inputValue: <GITHUB TOKEN>

  summary:
      description: Application demo.
      outputs: []
      notes: []